---
- name: add golang repository
  apt_repository: repo='ppa:ubuntu-lxc/lxd-stable'


- name: install (or update) golang
  apt:
    name: golang
    state: latest
    update_cache: yes
  tags: golang

- name: create go folder
  file:
      path=/opt/go mode=0775 owner=root group=vagrant
      state=directory
  tags: golang
  
- name: add go path environment variables
  lineinfile: dest=/etc/environment line="{{ item }}" insertafter=EOF
  with_items:
    - 'export GOPATH={{ go_path }}'
    - 'export GOBIN={{ go_path }}/bin'
    - 'PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin"'
  tags: golang
